### PR TITLE
Debugging without nw.js

### LINKED ISSUE #197: Opening a different log with the same name fails to load
I'm sure this is some artifact of the file open handler and this problem has been around forwever, but the scenarios is this:

It's common to log to an SD card and have the file named LOG00001.BFL.  Then open that log in BBE directly from the SD card.  Delete the file from the SD card, eject and go capture another log.  The new log's name is also LOG00001.BFL.  When trying to subsequently open the new log, BBE assumes the same file was chosen (because it's same name/path I'm guessing) and doesn't open the file - keeping the previously loaded data.  Opening another file before or quitting/restarting BBE is a workaround.

It's gotten me a few times while testing because I didn't notice that the new log didn't open and I was looking at the previous.  Maybe we can eliminate this efficiency check and just reopen the log always when the user specifies a file.

### PR DESCRIPTION
**Pull request by wolkesson**
Allow for debugging most of the application without rebuilding it. This saves a lot of time! It can now be run directly from the file system, with some limitations in video-export. In VS Code for example you may start a debug session with the follow contents in `.vscode/launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome",
            "url": "${workspaceFolder}/index.html",
            "webRoot": "${workspaceFolder}", 
        },
    ]
}
```
Or, you may run and edit directly in Chrome DevTools from filesystem.

Moved getManifestVersion in accordance to #207. 
Re-fixed #197, since latest Chrome (66.0.3359.181) doesn't support clearing a FileList.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ openLinksInExternalBrowserByDefault();
 
 $(document).ready(function () {
     // translate to user-selected language
-    localize();
+    if (isNW()) { localize(); }
```
Comment (McGiverGim) [inline index.js]: Does not work the localization under chrome?

If I'm not wrong, the standard coding of Betaflight is to not have all in the same line.

File: index.js [hunk 2]
```diff
@@ -53,20 +53,7 @@ function notifyOutdatedVersion(releaseData) {
...
-    var version = manifest.version_name;
-    if (!version) {
-        version = manifest.version;
-    }
-
-    return version;
-}
-
-checkForConfiguratorUpdates();
+if (isNW()) { checkForConfiguratorUpdates(); }
```
Comment (McGiverGim) [inline index.js]: The same. Does this not work under Chrome? And please, not all in the same line.

File: js/main.js [hunk 3]
```diff
@@ -942,7 +942,7 @@ function BlackboxLogViewer() {
             loadFiles(files);
 
             // Clear the files, in this way we can open a file with the same path/name again
-            e.target.files.clear();
+            e.target.value = "";
```
Comment (McGiverGim) [inline js/main.js]: Have you tested this in the standalone? I tested several ways until I fond the `clear()` but I don't remember if I tested the `value = ""` way.

Comment (McGiverGim) [reply js/main.js]: I've seen that you say that in some version this has changed... Is now working with your change?

File: index.js (hunk 1 above)
Comment (wolkesson) [reply index.js]: Localization uses the chrome.i18n API which is only available to extensions. It would of course be possible to build a shim, but since it's only used for translating strings of the version check and update, it's not of much use since that is anyway not possible to debug this way.

File: index.js (hunk 2 above)
Comment (wolkesson) [reply index.js]: This uses chrome.storage API which is also only available to extensions. Using localStorage would be possible, but then again the version check and update process is not possible to debug this way.

File: js/main.js (hunk 3 above)
Comment (wolkesson) [reply js/main.js]: It seems to work also in standalone. Tested this way:
1. Open a .bbl-file
2. Replace the file with another file with the same name, so that the path becomes identical.
3. Open the same file name again

**Comment by wolkesson** [comment]
Yes, you can just open the `ìndex.html` in Chrome and press F12 for development tools. Then you can also add breakpoints and do live edits. 
If you want to save those edits to the file system, you'll need to go to the source tab and then the filesystem tab on the left and add your source folder. (You will be asked for permission to change the files from the browser.) 
image
Now you can use Chrome as a quite good IDE!

File: js/tools.js [hunk 4]
```diff
@@ -447,4 +447,31 @@ function firmwareGreaterOrEqual(sysConfig, bf_version, cf_version) {
         return (sysConfig.firmwareType == FIRMWARE_TYPE_BETAFLIGHT  && semver.gte(sysConfig.firmwareVersion, bf_version)) || 
                (sysConfig.firmwareType == FIRMWARE_TYPE_CLEANFLIGHT && semver.gte(sysConfig.firmwareVersion, cf_version));
     }
+}
+
+function isNW(){
```
Comment (mikeller) [inline js/tools.js]: Please add a space before opening brackets.

File: js/main.js (hunk 3 above)
Comment (McGiverGim) [reply js/main.js]: Yes, then it seems to work. It is not needed to change the file, it must load again the same file if you ask for it.

**Comment by McGiverGim** [comment]
Yes. The pitty of this is that it will only work until the structure is changed, in the same way the configurator was.

But until then, is very useful.

File: js/tools.js [hunk 5]
```diff
@@ -447,4 +447,31 @@ function firmwareGreaterOrEqual(sysConfig, bf_version, cf_version) {
...
                (sysConfig.firmwareType == FIRMWARE_TYPE_CLEANFLIGHT && semver.gte(sysConfig.firmwareVersion, cf_version));
     }
-}
\ No newline at end of file
+}
+
+function isNW() {
+    try{
+        return (typeof require('nw.gui') !== "undefined");
+    } catch (e){
```
Comment (mikeller) [inline js/tools.js]: Another one. Sorry for not pointing this one out.
